repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: run-black
        name: Format all Python files with black
        entry: pdm run black .
        language: system
        types: [python]
        files: \.py$
      - id: run-isort
        name: Format all Python files with isort
        entry: pdm run isort .
        language: system
        types: [python]
        files: \.py$
